name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # Add this permission block

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build for multiple platforms
        run: |
          mkdir -p builds
          GOOS=linux GOARCH=amd64 go build -o builds/tcp_client_linux_amd64 .
          GOOS=windows GOARCH=amd64 go build -o builds/tcp_client_windows_amd64.exe .
          GOOS=darwin GOARCH=amd64 go build -o builds/tcp_client_darwin_amd64 .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
